CREATE TABLE `User` (
  `id` VARCHAR(191) NOT NULL, `googleId` VARCHAR(191) NOT NULL, `email` VARCHAR(191) NOT NULL, `name` VARCHAR(191) NOT NULL, `avatarUrl` VARCHAR(191) NULL, `slackTeamId` VARCHAR(191) NULL, `slackToken` VARCHAR(191) NULL, `slackChannel` VARCHAR(191) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `User_googleId_key`(`googleId`), UNIQUE INDEX `User_email_key`(`email`), PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `Sender` (
  `id` VARCHAR(191) NOT NULL, `userId` VARCHAR(191) NOT NULL, `fromEmail` VARCHAR(191) NOT NULL, `smtpUser` VARCHAR(191) NOT NULL, `smtpPass` VARCHAR(191) NOT NULL,
  PRIMARY KEY (`id`), CONSTRAINT `Sender_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `EmailJob` (
  `id` VARCHAR(191) NOT NULL, `userId` VARCHAR(191) NOT NULL, `senderId` VARCHAR(191) NOT NULL, `toEmail` VARCHAR(191) NOT NULL, `subject` VARCHAR(191) NOT NULL, `body` TEXT NOT NULL, `scheduledAt` DATETIME(3) NOT NULL, `delayMs` INTEGER NOT NULL, `hourlyLimit` INTEGER NOT NULL,
  `status` ENUM('SCHEDULED', 'QUEUED', 'SENT', 'FAILED', 'DELAYED_RATE_LIMIT') NOT NULL DEFAULT 'SCHEDULED', `bullJobId` VARCHAR(191) NULL, `sentAt` DATETIME(3) NULL, `error` TEXT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `EmailJob_bullJobId_key`(`bullJobId`), INDEX `EmailJob_status_scheduledAt_idx`(`status`, `scheduledAt`), PRIMARY KEY (`id`),
  CONSTRAINT `EmailJob_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT `EmailJob_senderId_fkey` FOREIGN KEY (`senderId`) REFERENCES `Sender`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
