import { Router } from 'express'; import { passport } from '../auth/google'; import { env } from '../config/env'; import { signSession } from '../auth/jwt'; import { requireAuth } from '../middleware/auth'; import { prisma } from '../db/prisma'; import crypto from 'crypto';

function hashPassword(password:string):string{return crypto.createHash('sha256').update(password).digest('hex');}

export const authRouter=Router();

authRouter.post('/register',async(req,res,next)=>{try{const {email,password,name}=req.body; if(!email||!password||!name)return res.status(400).json({error:'Email, password, and name are required'}); const existing=await prisma.user.findUnique({where:{email}}); if(existing)return res.status(400).json({error:'Email already registered'}); const user=await prisma.user.create({data:{email,password:hashPassword(password),name}}); res.cookie('reachinbox_session',signSession({id:user.id,email:user.email}),{httpOnly:true,sameSite:'lax',secure:env.FRONTEND_URL.startsWith('https')}).json({id:user.id,email:user.email,name:user.name});}catch(e){next(e);}});

authRouter.post('/login',async(req,res,next)=>{try{const {email,password}=req.body; if(!email||!password)return res.status(400).json({error:'Email and password are required'}); const user=await prisma.user.findUnique({where:{email}}); if(!user||!user.password||user.password!==hashPassword(password))return res.status(401).json({error:'Invalid email or password'}); res.cookie('reachinbox_session',signSession({id:user.id,email:user.email}),{httpOnly:true,sameSite:'lax',secure:env.FRONTEND_URL.startsWith('https')}).json({id:user.id,email:user.email,name:user.name});}catch(e){next(e);}});

authRouter.get('/google',(req,res,next)=>{if(!env.GOOGLE_CLIENT_ID)return res.status(503).json({error:'Google OAuth is not configured'}); passport.authenticate('google',{scope:['profile','email']})(req,res,next);});
authRouter.get('/google/callback',passport.authenticate('google',{session:false,failureRedirect:`${env.FRONTEND_URL}/login?error=google`}), (req,res)=>{const user=req.user as {id:string;email:string}; res.cookie('reachinbox_session',signSession(user),{httpOnly:true,sameSite:'lax',secure:env.FRONTEND_URL.startsWith('https')}).redirect(`${env.FRONTEND_URL}/dashboard`);});
authRouter.get('/me',requireAuth,async(req,res)=>res.json(await prisma.user.findUnique({where:{id:req.user!.id},select:{id:true,email:true,name:true,avatarUrl:true,slackChannel:true}})));
authRouter.post('/logout',(_req,res)=>res.clearCookie('reachinbox_session').status(204).end());
authRouter.get('/slack',requireAuth,(req,res)=>{if(!env.SLACK_CLIENT_ID)return res.status(503).json({error:'Slack OAuth is not configured'}); const state=signSession(req.user!); res.redirect(`https://slack.com/oauth/v2/authorize?client_id=${encodeURIComponent(env.SLACK_CLIENT_ID)}&scope=chat:write&redirect_uri=${encodeURIComponent(env.SLACK_REDIRECT_URI)}&state=${encodeURIComponent(state)}`);});
authRouter.get('/slack/callback',async(req,res)=>{try { const state=typeof req.query.state==='string'?req.query.state:''; const session=state?require('../auth/jwt').verifySession(state):null; if(!session||!env.SLACK_CLIENT_ID||!env.SLACK_CLIENT_SECRET)return res.redirect(`${env.FRONTEND_URL}/dashboard?slack=error`); const params=new URLSearchParams({client_id:env.SLACK_CLIENT_ID,client_secret:env.SLACK_CLIENT_SECRET,code:String(req.query.code||''),redirect_uri:env.SLACK_REDIRECT_URI}); const response=await fetch('https://slack.com/api/oauth.v2.access',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:params}); const data=await response.json() as any; if(!data.ok)throw new Error(data.error); await prisma.user.update({where:{id:session.id},data:{slackAccessToken:data.access_token ?? null,slackTeamId:data.team?.id ?? null,slackChannel:data.incoming_webhook?.channel_id ?? null,slackWebhookUrl:data.incoming_webhook?.url ?? null}}); res.redirect(`${env.FRONTEND_URL}/dashboard?slack=connected`); }catch{res.redirect(`${env.FRONTEND_URL}/dashboard?slack=error`);}});
authRouter.post('/slack/disconnect',requireAuth,async(req,res)=>{await prisma.user.update({where:{id:req.user!.id},data:{slackAccessToken:null,slackTeamId:null,slackChannel:null,slackWebhookUrl:null}});res.status(204).end();});
